import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import { Toaster } from "react-hot-toast";

import "./globals.css";

const fontSans = Be_Vietnam_Pro({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="Zftdnf6wi4wqCkSmEx_M8Z_GH37osudqdJa8efkBpYo"
        />
      </head>
      <body className={`${fontSans.className} antialiased`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
