import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

import "./globals.css";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";

const fontSans = Mona_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.className} antialiased`}>
        <NextTopLoader
          shadow={false}
          showSpinner={false}
          height={2}
          color="#ff0000"
        />
        <Header />
        <main className="pb-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
